### ISSUE TITLE
Составление автотестов не на функции из lib.py

### ISSUE THREAD

**Issue by amirismagilov** [amirismagilov/sportmaster_bonus_system#1]
В 0fd3955ed7e4ed2788a14fc76f1d14ed39508f0c в codecov < 100, но в lib.py codecov = 100, как покрыть тестами строки:
https://github.com/amirismagilov/sportmaster_bonus_system/blob/0fd3955ed7e4ed2788a14fc76f1d14ed39508f0c/app/main.py#L32
и 
https://github.com/amirismagilov/sportmaster_bonus_system/blob/0fd3955ed7e4ed2788a14fc76f1d14ed39508f0c/app/main.py#L35-L36

**Comment by coursar** [comment]
Пока никак

**Comment by coursar** [comment]
Посмотрел внимательнее - проблема в том, что с вашими данными (входными) вы никогда в эти условия не попадаете. 

Итого, чтобы покрыть main.py варианта два:
1. Вынести всё в функцию и вызывать с параметрами, так, чтобы эти ветки тоже отрабатывали
2. Проигнорировать файл main.py и выключить его из coverage

Чтобы реализовать второй вариант, нужно в корне проекта создать файл .coveragerc со следующим содержимым:
```ini
[run]
omit = app/main.py
```

И во флаги запуска pytest (pytest.ini) добавить:
```ini
--cov-config .coveragerc
```
